"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { CarbonCreditMarket } from "@/components/carbon-credit-market"
import { ArrowRight, Leaf, LineChart, TrendingUp } from "lucide-react"
import Link from "next/link"

export default function SustainabilityPage() {
  return (
    <div className="container py-10">
      <h1 className="text-3xl font-bold mb-6">Sustainability & Carbon Credits</h1>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-3 mb-8">
        <Card>
          <CardContent className="p-6">
            <div className="flex flex-col items-center space-y-2">
              <Leaf className="h-8 w-8 text-green-600" />
              <h3 className="text-xl font-medium">Carbon Credits</h3>
              <p className="text-3xl font-bold">12,500+</p>
              <p className="text-sm text-muted-foreground text-center">
                Carbon credits generated by farms on our platform
              </p>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex flex-col items-center space-y-2">
              <TrendingUp className="h-8 w-8 text-green-600" />
              <h3 className="text-xl font-medium">Market Value</h3>
              <p className="text-3xl font-bold">$187,500</p>
              <p className="text-sm text-muted-foreground text-center">Total value of carbon credits on our platform</p>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex flex-col items-center space-y-2">
              <LineChart className="h-8 w-8 text-green-600" />
              <h3 className="text-xl font-medium">CO₂ Reduction</h3>
              <p className="text-3xl font-bold">12,500 tons</p>
              <p className="text-sm text-muted-foreground text-center">
                Carbon dioxide equivalent reduced or sequestered
              </p>
            </div>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="market">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="market">Carbon Credit Market</TabsTrigger>
          <TabsTrigger value="practices">Sustainable Practices</TabsTrigger>
        </TabsList>

        <TabsContent value="market" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle>Carbon Credit Market</CardTitle>
              <CardDescription>Browse and purchase carbon credits from sustainable farms.</CardDescription>
            </CardHeader>
            <CardContent>
              <CarbonCreditMarket />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="practices" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle>Sustainable Farming Practices</CardTitle>
              <CardDescription>
                Learn about the sustainable farming practices that generate carbon credits.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">No-Till Farming</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      Minimizes soil disturbance, reduces erosion, and increases carbon sequestration in the soil.
                    </p>
                    <div className="mt-4">
                      <p className="text-sm font-medium">Carbon Credit Potential:</p>
                      <p className="text-sm">0.5-1.5 tons CO₂e per acre per year</p>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">Cover Crops</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      Plants grown between main crop seasons to protect soil, reduce erosion, and capture carbon.
                    </p>
                    <div className="mt-4">
                      <p className="text-sm font-medium">Carbon Credit Potential:</p>
                      <p className="text-sm">0.3-1.0 tons CO₂e per acre per year</p>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">Rotational Grazing</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      Moving livestock between pastures to allow grass recovery and carbon sequestration.
                    </p>
                    <div className="mt-4">
                      <p className="text-sm font-medium">Carbon Credit Potential:</p>
                      <p className="text-sm">1.0-2.0 tons CO₂e per acre per year</p>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">Agroforestry</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      Integrating trees with crops or livestock to enhance biodiversity and carbon storage.
                    </p>
                    <div className="mt-4">
                      <p className="text-sm font-medium">Carbon Credit Potential:</p>
                      <p className="text-sm">2.0-5.0 tons CO₂e per acre per year</p>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">Methane Capture</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      Capturing methane from livestock waste for energy production or flaring.
                    </p>
                    <div className="mt-4">
                      <p className="text-sm font-medium">Carbon Credit Potential:</p>
                      <p className="text-sm">Variable based on herd size and system</p>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">Precision Agriculture</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      Using technology to optimize inputs and reduce emissions from fertilizers.
                    </p>
                    <div className="mt-4">
                      <p className="text-sm font-medium">Carbon Credit Potential:</p>
                      <p className="text-sm">0.2-0.5 tons CO₂e per acre per year</p>
                    </div>
                  </CardContent>
                </Card>
              </div>

              <div className="mt-8 text-center">
                <p className="text-muted-foreground mb-4">Are you a farmer interested in earning carbon credits?</p>
                <Link href="/farmer/dashboard">
                  <Button>
                    Go to Farmer Dashboard
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}

